Add hooks and pages for authentication
alizahid/ello pull request #7
Opened 2022-04-03 01:03 UTC by sidletski

2022-04-03 01:31 UTC, alizahid requested changes

2022-04-03 01:31 UTC, alizahid commented on src/components/common/form/index.tsx
> +import { FunctionComponent } from 'react'
Let's not use this approach. It's too messy, hard to style, and internationalize. Best to rely on HTML validation constraints API. Use plain `form`.

2022-04-03 01:31 UTC, alizahid commented on src/components/common/message/index.tsx
> +import React, { FunctionComponent } from 'react'
❤️😂

2022-04-03 01:31 UTC, alizahid commented on src/pages/auth/sign-in.tsx
> +      router.push('/dashboard')
```suggestion
      router.push('/app')
```

2022-04-03 01:31 UTC, alizahid commented on src/hooks/auth/sign-in.ts
> +  signIn: (data: { email: string; password: string }) => Promise<void>
We're doing password-less auth with magic links.

2022-04-03 01:31 UTC, alizahid commented on src/utils/withGuestRequired.ts
> +type GuestHocProps = {
Move this to `types/next.ts` and rename to `Context`.

2022-04-03 01:31 UTC, alizahid commented on src/pages/api/auth/[...supabase].ts
> +  logout: { returnTo: '/' }
Spread them brackets!

2022-04-03 01:31 UTC, alizahid commented on src/utils/withGuestRequired.ts
> +  } catch (e) {}
Go max verbosity! `error`

2022-04-03 01:31 UTC, alizahid commented on src/utils/withGuestRequired.ts
> +  } catch (e) {}
```typescript
catch (error) {
  //
}
```

2022-04-03 01:31 UTC, alizahid commented on src/pages/api/auth/[...supabase].ts
> +  logout: { returnTo: '/' }
```suggestion
  logout: {
    returnTo: '/'
  }
```

2022-04-03 13:53 UTC, alizahid requested changes

2022-04-03 13:53 UTC, alizahid commented on src/hooks/auth/sign-in.ts
> +  const signIn = useCallback<Returns['signIn']>(async (email) => {
```suggestion
  const signIn: Returns['signIn'] = useCallback(async (email) => {
```

2022-04-03 13:53 UTC, alizahid commented on src/hooks/auth/sign-in.ts
> +    setLoading(false)
I'd move this after error or success.

2022-04-03 13:53 UTC, alizahid commented on src/utils/withUserRequired.ts
> +    const { data: userData } = await supabaseClient
Why rename? Is there a conflict?

2022-04-03 13:53 UTC, alizahid commented on src/pages/auth/sign-up.tsx
> +        <Message className="mt-8" type={MessageType.Success}>
```suggestion
        <Message className="mt-6" type={MessageType.Success}>
```

2022-04-03 13:53 UTC, alizahid commented on src/pages/auth/sign-up.tsx
> +            className="mt-4"
```suggestion
            className="mt-3"
```

2022-04-03 13:53 UTC, alizahid commented on src/pages/auth/sign-up.tsx
> +            className="mt-4"
```suggestion
            className="mt-3"
```

2022-04-03 13:53 UTC, alizahid commented on src/pages/auth/sign-up.tsx
> +          {error && (
Error should be at the start of the form with `mb-6`.

2022-04-03 13:53 UTC, alizahid commented on src/utils/withGuestRequired.ts
> +export const withGuestRequired: GetServerSideProps = async ({
I think the name here is confusing. What does guest required do?

2022-04-03 13:53 UTC, alizahid commented on src/pages/auth/sign-in.tsx
> +        <Message className="mt-8" type={MessageType.Success}>
Same styles as the other page.

2022-04-03 13:53 UTC, alizahid commented on src/pages/auth/sign-in.tsx
> +          Check your email for a magic link
Also need to intl-ize all strings.

2022-04-03 15:54 UTC, sidletski commented on src/utils/withUserRequired.ts
> +    const { data: userData } = await supabaseClient
Just to clearify, but I can rename it

2022-04-03 21:19 UTC, alizahid requested changes

2022-04-03 21:19 UTC, alizahid commented on src/hooks/auth/sign-in.ts
> +import { supabaseClient } from '@supabase/supabase-auth-helpers/nextjs'
Looks like we aren't actually using this. So let's use `supabase` from `lib/supabase.ts`.

2022-04-03 21:19 UTC, alizahid commented on src/hooks/auth/sign-up.ts
> +    setSuccess(undefined)
```suggestion
    setSuccess(false)
```

2022-04-03 21:19 UTC, alizahid commented on src/i18n/en.json
> +  "sign_in_success": "Check your email for a magic link",
I think Supabase `signIn` creates an account if it doesn't exist so we don't need a sign up page, only a sign in page.

2022-04-03 21:19 UTC, alizahid commented on src/pages/app.tsx
> +  onboarded: true
`onboarded` should be `false` here, no? Else why are we onboarding them again?

2022-04-03 21:19 UTC, alizahid commented on src/utils/withUserCheck.ts
> +  let defaultRedirectUrl = ''
This try-catch is very lazy. 😂

2022-04-03 21:19 UTC, alizahid commented on src/utils/withUserCheck.ts
> +  let defaultRedirectUrl = ''
Why throw when we can just return?

2022-04-03 21:19 UTC, alizahid commented on src/hooks/auth/sign-up.ts
> +export const useSignUp = (): Returns => {
We can drop the sign up page in favor of sign in. Supabase lets you sign up with just `email`.

2022-04-03 21:36 UTC, sidletski commented on src/i18n/en.json
> +  "sign_in_success": "Check your email for a magic link",
`signUp` requires a password while `signIn` doesn't

2022-04-03 21:37 UTC, sidletski commented on src/pages/app.tsx
> +  onboarded: true
`/app` route requires onboarded user, it's only the `/auth/onboarding` page requires authenticated and non-onboarded user

2022-04-03 21:37 UTC, sidletski commented on src/utils/withUserCheck.ts
> +  let defaultRedirectUrl = ''
Just don't want to duplicate
`redirect: {
    destination: redirectTo ?? defaultRedirectUrl,
    permanent: false
}`
for every condition

2022-04-03 21:38 UTC, alizahid commented on src/i18n/en.json
> +  "sign_in_success": "Check your email for a magic link",
We don't need `signup` because `signIn` does both.

2022-04-03 21:39 UTC, alizahid commented on src/pages/app.tsx
> +  onboarded: true
Shit, the expor name was `Onboarding` so I thought it was the onboarding page. Didn't look at the path. All good!

2022-04-03 21:42 UTC, sidletski commented on src/pages/app.tsx
> +  onboarded: true
My bad!

2022-04-03 21:42 UTC, alizahid commented on src/utils/withUserCheck.ts
> +  let defaultRedirectUrl = ''
Use default values on the argument, then.

```typescript
export const withUserCheck = (options: CheckOptions = {
  xyz = 123
}) => {
```

2022-04-04 01:54 UTC, alizahid commented on src/providers/user.tsx
> +    checkSession()
I don't think we need this every time the path changes?

2022-04-04 01:56 UTC, alizahid requested changes

2022-04-04 01:56 UTC, alizahid commented on src/utils/withUserCheck.ts
> +  const { data } = await supabase.from('User').select('*').eq('email', email)
```suggestion
  const { data } = await supabase.from('User').select('*').eq('email', email).single()
```

This will fetch just one record.

2022-04-04 13:08 UTC, sidletski commented on src/utils/withUserCheck.ts
> +  let defaultRedirectUrl = ''
In this case we'll have unnecessary redirect. For example, user's trying to get access to the `/app` page while he's neither authenticated nor onboarded. If we set `/auth/onboarding` page as a redirect route then he'll be redirected to the `/auth/onboarding` and then onboarding guard will redirect him to the `/auth/sign-in` page
This will not cause any issues as long as we try to keep our guards simple, just one extra redirect

2022-04-04 13:39 UTC, alizahid requested changes

2022-04-04 13:39 UTC, alizahid commented on src/utils/withUserCheck.ts
> +  if (!data || data.length === 0) {
Now that you're doing `single`, you don't have to check for length anymore.

2022-04-04 13:39 UTC, alizahid commented on src/pages/api/auth/index.ts
> +}
```suggestion
const handler: NextApiHandler = (req, res): void =>
  supabase.auth.api.setAuthCookie(req, res)
```

2022-04-04 13:39 UTC, alizahid commented on src/providers/user.tsx
> +  const { pathname, push: pushRoute } = useRouter()
I'd advise against destructuring `useRouter`.

2022-04-04 13:39 UTC, alizahid commented on src/utils/withUserCheck.ts
> +export const withUserCheck = (options: CheckOptions = {}) => {
I think `authenticated` and `onboarded` should be `true` by default so pages that require auth don't have to pass it again and again. Also `redirectTo` should be `/auth/sign-in` by default. Then the auth pages (sign up, sign in, onboarding) can override as needed.

2022-04-04 13:39 UTC, alizahid commented on src/utils/withUserCheck.ts
> +      } else {
Don't need `else` statements when we're returning. Will make the code a lot more readable!

2022-04-04 13:39 UTC, alizahid commented on src/utils/withUserCheck.ts
> +  redirectTo?: string
Since we're doing the full logic in the function, I think we can drop `redirectTo`? The other two fields can determine where we'll redirect the user?

2022-04-04 15:33 UTC, alizahid approved these changes

2022-04-04 15:42 UTC, merged